[versions]
agp = "8.0.2"

nav = "2.5.3"

appcompat = "1.6.1"
material = "1.9.0"
work = "2.8.1"

gson = "2.10.1"
mmkv = "1.3.0"
treeview = "1.1.4"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

nav-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "nav" }
nav-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "nav" }

work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

treeview = { group = "io.github.amrdeveloper", name = "treeview", version.ref = "treeview" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
nav-safeargs = { id = "androidx.navigation.safeargs", version.ref = "nav" }

[bundles]

